version: 2

models:
  - name: silver_gesellschaften
    description: "Cleaned company data"
    columns:
      - name: gesellschaft_id
        tests:
          - not_null
          - unique

  - name: silver_mitarbeiter
    description: "Cleaned employee data"
    columns:
      - name: mitarbeiter_id
        tests:
          - not_null
          - unique

  - name: silver_umsatz
    description: "Cleaned sales data"
    columns:
      - name: umsatz_id
        tests:
          - not_null
          - unique
