version: 2

models:
  - name: silver_gesellschaften
    description: "Cleaned company data"
    columns:
      - name: gesellschaft_id
        tests:
          - not_null
        

  - name: silver_mitarbeiter
    description: "Cleaned employee data"
    columns:
      - name: gesellschaft_id
        tests:
          - not_null
          

  - name: silver_umsatz
    description: "Cleaned sales data"
    columns:
      - name: gesellschaft_id
        tests:
          - not_null
          
