# models/bronze/schema.yml

version: 2

sources:
  - name: public     
    tables:
      - name: raw_umsatz
      - name: raw_gesellschaften
      - name: raw_mitarbeiter


models:
  - name: bronze_gesellschaften
    description: "Raw data about companies"
    columns:
      - name: gesellschaft_id
        tests:
          - not_null
          - unique
      - name: gesellschaft_name
        tests:
          - not_null
      - name: standort
        tests:
          - not_null
      - name: branche
        tests:
          - not_null

  - name: bronze_mitarbeiter
    description: "Raw data about employees"
    columns:
      - name: gesellschaft_id
        tests:
          - not_null
          - relationships:
              to: ref('bronze_gesellschaften')
              field: gesellschaft_id

  - name: bronze_umsatz
    description: "Raw sales data"
    columns:
      - name: gesellschaft_id
        tests:
          - not_null  
      - name: umsatz_eur
        tests:
          - not_null